### ISSUE TITLE
[Roadmap] BigCodeBench Q3 2024 Roadmap

### ISSUE THREAD

**Issue by terryyz** [bigcode-project/bigcodebench#45]
This document includes the features of BigCodeBench Q3 2024. Please feel free to discuss and contribute, as this roadmap is shaped by the BigCodeBench community.

### Help Wanted
- [ ] Lingering processes #42 
- [ ] Better documentation #40, #41 
- [ ] Dataset Repair, e.g., #33 

### Feature
- [x] Batch generation (to be released)
- [x] Customized direct completion setup (to be released)

### Dataset
- [ ] More investigations on the BigCodeBench tasks

### Ongoing Research
- [ ] Benchmarking more languages -- Verilog & R, cc @shailja-thakur @ThreeCirclesK @marianna13
- [ ] Agentic Evaluation ([proof-of-concept infra](https://github.com/JoshuaPurtell/SmallBench) to be scaled up), cc @JoshuaPurtell
- [ ] Grounded Zero-Shot Tool Use, cc @terryyz @siviltaram
